name = "wechat-verify"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# 開發環境配置
[dev]
port = 8787
local_protocol = "http"

# 生產環境配置
[env.production]
route = { pattern = "unify-it.fun/*", custom_domain = true }

# 緩存配置
[cache]
no_cache = true

# 請將下面的 your_zone_id 替換為您的實際 zone ID
# routes = [
#   { pattern = "unify-it.fun/*", zone_id = "your_zone_id" }
# ] 